### ISSUE TITLE
Initial date not selected

### ISSUE THREAD

**Issue by Micha10** [ngneat/input-mask#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If adding a mask, and opening the dropdown-calendar, the initial date is not selected automatically

## Expected behavior

for example: 
typescipt:
`public pickervalue:string = "2023-12-10"`
now using ngmodel to bind the pickervalue to the input.

Now running the app. The value is displayed in the input. Now opening the calender popup. The date of the model is not selected (but today seems to be selected).

*If you just remove the input mask, the control is working as expected.*

If you select a date with the datepicker an reopen the popup, the new value is selected (as expected for the first time)

https://github.com/ngneat/input-mask/assets/19784992/e17abfcf-acb4-46b1-b69a-63b2697bfa95

## Minimal reproduction of the problem with instructions

You can find a small demo here: https://github.com/Micha10/noinitdatewithmask

## What is the motivation / use case for changing the behavior?

If there's an initial value and you just open the popup calender, the date should be selected as wiithout inputmask

## Environment

<pre><code>
Angular version: 15+

Browser:
- [x] Chrome (desktop) version latest
- [x] Firefox version latest
 
For Tooling issues:
- Node version: 18.16
- Platform:   Windows 

</code></pre>

**Comment by shhdharmen** [comment]
You're trying to use features from 2 libraries together: Angular Material Datepicker and @ngneat/input-mask. They both rely differently on input events. And hence, it's not recommended to use both of them together.
