### ISSUE TITLE
Validation does not respect optional fields

### ISSUE THREAD

**Issue by antch** [ngneat/input-mask#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Empty inputs without `required="true"` fail validation.

## Expected behavior

The form control should be considered valid if it is empty (`''`, `null`, `undefined`).

## Minimal reproduction of the problem with instructions

Add `[required]="false"` to any of the inputs in the Stackblitz linked in the README, and observe that `isValid` still shows as `true` and there is an entry in the errors object.

## What is the motivation / use case for changing the behavior?

There is no way to represent a non-required masked field currently. The behavior of Angular's built-in validators is that they do not validate empty inputs, and leave that to the "required" validator instead. The input-mask validator should be consistent with this.

## Environment

<pre><code>
Angular version: 11

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12
- Platform:  OSX

Others:
I tried to find a workaround using native inputmask options but was not able to get anything to work.
</code></pre>

**Comment by shhdharmen** [comment]
@antch What entry are you seeing in error object?

**Comment by shhdharmen** [comment]
@antch Inputmask's validation works on [`isvalid`](https://github.com/RobinHerbots/Inputmask#isvalid) method. It has nothing to do with `required` of your input.

**Comment by antch** [comment]
@shhdharmen Yes, you can see on [the project's Stackblitz](https://stackblitz.com/edit/angular-ivy-6greu1?file=src/app/app.component.ts) that for empty inputs they all have `{ "inputMask": false }`. How would one configure the form to handle a masked field that is also not required without having errors on empty input? There is no way that I can see using the inputmask library to make a mask completely optional (for example `[99/99/9999]`), and for that reason it seems like this library should accommodate that somehow.

**Comment by shhdharmen** [comment]
@antch your question is not related to this library, but more of how you should solve your problem. 🙂  You can ask your question on related platforms, like stack-overflow.

Just to give you idea, for particular errors, you should check only that error. For example, if you want to handle `required` error, then you should check `errors.required` and not `errors.inputMask`.

**Comment by antch** [comment]
I respectfully disagree that it isn't related to this library as a non-required masked input is a very common use-case. I certainly understand what you're saying regarding checking individual errors, but that does not help for things like styling `.ng-invalid` elements and/or components that do generic error display.

For example, Angular's built-in `Pattern` validator will not generate an error for an empty input at all, and instead you'd use the `Required` validator to catch that case. It seems like this library should behave consistently along the same lines, and never generate errors for empty inputs.

**Comment by shhdharmen** [comment]
@antch I respectfully disagree, too. 🙂 That's not how Angular's validations work.

To make it easy to understand for you:

1. Please visit this stackblitz: https://stackblitz.com/angular/povqbjeqrpy?file=src/app/reactive/hero-form-reactive.component.html
2. On line 16, there is condition to show/hide error: `*ngIf="name.invalid && (name.dirty || name.touched)"`
3. See that condition again: `*ngIf="name.invalid && (name.dirty || name.touched)"`
4. They're not only checking for `invalid`, but they are also checking if `name` `FormControl` should be `touched` or `dirty`
5. Now, try to update the condition with this `*ngIf="name.invalid"
6. You will see all the errors, without even touching the form

I would request you to visit Angular's documentation about [reactive form validation](https://angular.io/guide/form-validation#validating-input-in-reactive-forms).

**Comment by antch** [comment]
I've gone ahead and modified the Stackblitz, removing the "required" validators, just a little to illustrate what I'm talking about a little better:

https://stackblitz.com/edit/angular-iupvfm?file=src%2Fapp%2Freactive%2Fhero-form-reactive.component.html

Now, if you clear out the "Name" field (in either form) you will NOT see the red styling on the input field. If either the `minLength` or `forbiddenNameValidator` treated empty inputs as invalid like the validator in input-mask does, you would erroneously see the red styling as if the field was invalid. This is because the styling is based on ANY ERROR being applied.

Even looking at `forbiddenNameValidator` you can see that it purposely ignores empty values:
```
   return forbidden ? {forbiddenName: {value: control.value}} : null;
```

`minLength` does the same thing, it purposely leaves validation of empty inputs to the `required` validator.

**Comment by shhdharmen** [comment]
@antch Ok, yeah, I got it now what you were trying to say all this time. I really enjoyed this healthy conversation.

It would be great if you could generate a PR with fix and contribute to this project.

**Comment by antch** [comment]
Sure, I can do that. I'll try to get some time this weekend.

**Comment by antch** [comment]
I want to preface by saying I'm not sure this is the right place to discuss this, let me know if there's a better place.

Just an update here, I did get the change working but it surfaced that the current unit test around validation is not actually working properly right now -- it will always show as invalid since the date and IP fields cannot be typed in and will always be blank. I added a simple masked field in the spec to check validation against which takes care of it. I'm also considering whether or not there would be value in adding an input that uses `ngModel` instead of reactive forms as a part of the spec. What do you think?

**Comment by shhdharmen** [comment]
Yeah, you can make appropriate changes. Let us know once you create a PR and we can review everything in one go.

**Comment by jongbonga** [comment]
I'm not sure if I should address it here or create a new issue for what I encountered, I'm also not sure if the issue is even related but for some reason, my `validators` params are being overwritten by `{ "inputMask": false }`

**Comment by shhdharmen** [comment]
@jongbonga please create new issue.
