### ISSUE TITLE
Support for angular 12

### ISSUE THREAD

**Issue by pzontrop** [ngneat/input-mask#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Unable to install on an angular 12 app by running `ng add @ngneat/input-mask` with following error message:
```
npm ERR! Found: @angular/common@12.1.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.2.7" from @ngneat/input-mask@1.0.2
```

## Expected behavior

Successfull install

## Minimal reproduction of the problem with instructions
update angular cli and create an empty project using the cli and run `ng add @ngneat/input-mask`

## What is the motivation / use case for changing the behavior?
I would like to use your plugin in an angular 12 app.

## Environment

<pre><code>
Angular version: 12.1.5

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v16.1.0  
- Platform:  Mac 

</code></pre>

**Comment by shhdharmen** [comment]
You're most welcome to create a PR. I think you will just need to update angular version in library's `package.json`.

**Comment by pzontrop** [comment]
Done... I left the internal angular version of the library at 11 but updated the peer dependency to also accept 12. At first I also updated the internal dependencies but I don't think it's necessary. Let me know if you want me to update them as well.

BTW I noticed the tests are broken. Didn't want to fix them in this pullrequest as it was not related to my code
