### ISSUE TITLE
Custom component (ionic) support

### ISSUE THREAD

**Issue by jongbonga** [ngneat/input-mask#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

TypeError: Cannot read property 'charAt' of undefined

## Expected behavior

Being able to use a mask on custom/wrapper components (ionic) `ion-input`.

## Minimal reproduction of the problem with instructions

```
numericMask = createMask({ alias: 'numeric' });

<ion-input
          type="password"
          inputmode="tel"
          clearInput="true"
          minlength="4"
          maxlength="10"
          [inputMask]="numericMask"
        ></ion-input>
```

https://ionic-qesceu.stackblitz.io/

## What is the motivation/use case for changing the behavior?

Not really a change of behavior but more of a feature request (if not currently implemented)

## Environment

```
Ionic:

   Ionic CLI                     : 6.17.0 (/Users/jonathan/.nvm/versions/node/v16.4.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 12.0.3
   @angular-devkit/schematics    : 12.0.3
   @angular/cli                  : 12.0.3
   @ionic/angular-toolkit        : 4.0.0
```

<pre><code>
Angular version: 12.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.4.2  
- Platform:   Mac

</code></pre>

Others: [Here](https://github.com/amarkes/br-mask) is a library that supports it but isn't maintained anymore

**Comment by shhdharmen** [comment]
The example used Angular v5, we don't support that version.

**Comment by jongbonga** [comment]
Hi

my project uses angular 12 like initially posted. The example is just to illustrate the behavior on ionic and not angular.

i will provide an updated example shortly

**Comment by jongbonga** [comment]
@shhdharmen [here](https://ionic-5-angular-10-start-template-xdewt8.stackblitz.io) is the same behabior on Angular 10

**Comment by jongbonga** [comment]
Is Angular 12 supported? is yes, [Here](https://ionic-5-angular-12-start-template-tabs-ybiusv.stackblitz.io) we go

**Comment by shhdharmen** [comment]
@jongbonga I understood that you want support for ionic from this library. As this is a new feature request, I will keep it open and let's see it's demand, or if anyone wants to pick and fix it, that would also be great.

**Comment by shhdharmen** [comment]
@jongbonga `ion-input` is not native `input`, that's why `inputmask` is not working.

To solve it, I can add one more `@Input` called `inputMaskElement`, in which we can pass native `input` from `ion-input` using [`getInputElement`](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.tsx#L285).

I will look into this more.

**Comment by jongbonga** [comment]
@shhdharmen that would be amazing 🙏🏽

**Comment by shhdharmen** [comment]
For usage with ionic, I have added one separate module `InputMaskIonicModule`. More at: https://github.com/ngneat/input-mask#ionic

**Comment by Burgov** [comment]
I now have to install `@ionic/angular` if i want to use this library. is that intended? I'm not using ionic in my project...

![Screenshot 2021-09-13 at 10 25 25](https://user-images.githubusercontent.com/417674/133049787-9c4a9767-8556-4b58-a3bd-de92907edeb6.png)

**Comment by shhdharmen** [comment]
Reverted the changes. I will have to think more about ionic support.

**Comment by DwieDima** [comment]
Does it support `ion-input` now?
Is there any workaround we can use?

**Comment by DwieDima** [comment]
My workaround is to use the library [inputmask](https://github.com/RobinHerbots/Inputmask) directly. 
To make this work with `ion-input`, you have bind it to the native input. Heres a example with ionic angular:

```
npm install inputmask --save
```

```typescript
import Inputmask from 'inputmask';

@ViewChild('maskedInput', { read: IonInput }) private _input: IonInput;

  public async ionViewDidEnter(): Promise<void> {
    const im = new Inputmask('(9999 9999 9999 9999)', {
      // for more options see doc
      placeholder: '',
      casing: 'upper',
    });

    const nativeInput = await this._input.getInputElement();
    im.mask(nativeInput);
  }

```

```html

...

    <ion-item lines="full">
      <ion-label position="stacked">masked input</ion-label>
      <ion-input type="text" #maskedInput></ion-input>
    </ion-item>

...

```

Using this approach, you'll lose any build in form validation (like reactive forms).
You have to check this by your own (e.g. using regex pattern for reactive form).

**Comment by jongbonga** [comment]
> Does it support `ion-input` now? Is there any workaround we can use?

You have set the input selector in the module imports like this 

`InputMaskModule.forRoot({ inputSelector: 'input', isAsync: true })`
