### ISSUE TITLE
PatchValue of masked input with unmasked value

### ISSUE THREAD

**Issue by jongbonga** [ngneat/input-mask#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Field with input mask doesn't get updated when `patchValue` is used with `autoUnmask` value.

## Expected behavior

Input with the mask to accept the raw value

## Minimal reproduction of the problem with instructions

I have a 

```
phoneInputMask = createMask({
    mask: '(999) 999-99-99',
    autoUnmask: true
});
```

on a `<input formControlName="phone" type="tel" [inputMask]="phoneInputMask"/>` that needs to be populated with `form.patchValue(phone)`. 
I assume the issue is due to the raw value (0123456789) not matching the initial mask: '(999) 999-99-99'. 

## What is the motivation / use case for changing the behavior?

To patchValue() of a masked input with an unmasked value

## Environment

<pre><code>
Angular version: 12.1.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.4.2  
- Platform:  Mac

</code></pre>

**Comment by shhdharmen** [comment]
Can you please create stackblitz to show this error?
