### ISSUE TITLE
Parser function not working on latest stable?

### ISSUE THREAD

**Issue by GKersten** [ngneat/input-mask#36]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I update the package to latest 3.0.4, you can see that the Datetime example is not converting to Date object, but simply returning the string value in the inputFormat

## Expected behavior
In the [original Stackblitz example ](https://stackblitz.com/edit/angular-ivy-6greu1?file=src/app/app.component.ts) provided by the readme, we can see the `parser` function do it's work. But this example is still pointing to an older(?) package "beta".

## Minimal reproduction of the problem with instructions
Took the original Stackblitz example, updated the package to v 3.0.4: See [updated Stackblitz](https://stackblitz.com/edit/ngneat-inputmask-parser)

## Environment
<pre><code>
Angular version: 11.0.8

Browser:
- [X] Chrome (desktop) version 95.0.4638.54
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by shhdharmen** [comment]
How did you install our lib in version `11.0.8`? We only support versions `>= 11.2.7 < 13`.

I agree that parser is not working on stackblitz, but it's working if you run your code locally.
