### ISSUE TITLE
Dynamically changing [inputMask] variable not updating input

### ISSUE THREAD

**Issue by GKersten** [ngneat/input-mask#37]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Whenever I update the variable bound to the `[inputMask]` directive, it is not updating the actual mask on the input

## Expected behavior
Expect that when I make changes to the variable it would actually update the mask that is being used on the input.

## Minimal reproduction of the problem with instructions
Created a [Reproduction on Stackblitz](https://stackblitz.com/edit/ngneat-input-mask-dynamic) you can see whenever you try to change the `[inputMask]="textInputMask"` it will not update the mask for the input. Only when you enable the work-around in the .ts file. You will see I force the refresh of the input to make it actually work.

## What is the motivation / use case for changing the behavior?
Would make sense to listen for @ Input variables

## Environment
<pre><code>
Angular version: 11.2.13

Browser:
- [x] Chrome (desktop) version 95.0.4638.69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by shhdharmen** [comment]
This is quite difficult and time-consuming. PR is most welcome. I started working on some time back, it's at https://github.com/ngneat/input-mask/tree/feature/handle-changes if you want to have a look.

**Comment by penihel** [comment]
I think you should take advantage of this change and add the ability to add or remove the mask by the result of a function.

Today if I pass "null", an error occurs

**Comment by KthProg** [comment]
How are we supposed to work around this?
