### ISSUE TITLE
FormControl valueChanges not triggered when pasting value

### ISSUE THREAD

**Issue by GKersten** [ngneat/input-mask#38]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Whenever I paste a value to an input that has the [inputMask] directive, the related [formControl] is not emitting the `.valueChanges` event.

## Expected behavior

When I actually remove the [inputMask] on that input, I can actually see this working normally, so this seem to be caused by the [inputMask] directive

## Minimal reproduction of the problem with instructions

See reproduction on [StackBlitz](https://stackblitz.com/edit/ngneat-input-mask-no-valuechanges). Try to enter any value in the "Input" field, notice that there are console logs. Now try to paste some value in that input like "123", notice there is no console log, there was no event emitted to valueChanges.

Try to remove the [inputMask] on the <input /> and you should see it actually does a console log when pasting values.

## What is the motivation / use case for changing the behavior?

Should work as a normal FormControl

## Environment

<pre><code>
Angular version: 11.2.13

Browser:
- [ ] Chrome (desktop) version 95.0.4638.69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by GKersten** [comment]
I found this on the inputMask library repo: https://github.com/RobinHerbots/Inputmask/pull/2543 Seems to be related, but trying to update to the current latest beta ("inputmask": "5.0.7-beta.23") of that package was not solving the issue. Not sure if this PR is already included in one of the published packages.

**Comment by alexandrbig** [comment]
@GKersten hello, the PR was merged in, but the code was modified and no `input` event triggered anymore.

**Comment by shhdharmen** [comment]
As this issue is already present in original lib, closing here.
