### ISSUE TITLE
v4: inputmask__WEBPACK_IMPORTED_MODULE_0__ is not a constructor

### ISSUE THREAD

**Issue by ssougnez** [ngneat/input-mask#40]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I used to create a mask using this:

`public nissMask = createMask('99.99.99-999.99');`

It worked very well with the version 3 but since the version 4, I get:

![image](https://user-images.githubusercontent.com/10199821/141703057-4789ddf9-1fe9-4a01-b021-d1a90406f9c9.png)

## Expected behavior

The mask should be applied

## Minimal reproduction of the problem with instructions

Simply create a mask using:

`public nissMask = createMask('99.99.99-999.99');`

Then bind it like this:

`<input type="text" [inputMask]="nissMask" formControlName="niss" />`

## What is the motivation / use case for changing the behavior?

/

## Environment

<pre><code>
Angular CLI: 13.0.2
Node: 14.16.1
Package Manager: yarn 1.22.4
OS: win32 x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4

Browser:
- [x] Edge version 95
 
For Tooling issues:
- Node version: 14.16
- Platform:  Windows 10
</code></pre>

## Environment

I reverted to v3 and it works (although ng cli tells me to encourage you to migrate to Ivy :-))

**Comment by shhdharmen** [comment]
Can you please create a repo or stackblitz which reproduces that error?

**Comment by shhdharmen** [comment]
We will take care of this in #42.
