### ISSUE TITLE
Update to Angular v13

### ISSUE THREAD

**Issue by shhdharmen** [ngneat/input-mask#42]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Library doesn't support Angular v13.

## Expected behavior

Library should support Angular v13.

## What is the motivation / use case for changing the behavior?

Keeping up with latest Angular versions.

**Comment by shhdharmen** [comment]
@arturovt do you want to pick this up? Your last PR #39 introduced some issues (#40), so I reverted it back. This time we will test it properly before merging.

**Comment by arturovt** [comment]
Well, it wasn't worth reverting it back and publishing 4.0.1 since the developer could use the 3.x version and just skip peer dependency check. The library would just go through `ngcc` compiler.

I'll check the 4.0 version within the ng13 playground.

**Comment by shhdharmen** [comment]
If our library says it supports v13, then it should support v13. We should not ask developers to do anything to get rid of bug unless required. At least I believe so... 🙂

With the revert, now `ng add... ` will not allow them to install the library in Angular v13, that's the right approach.

Thanks for your support 👍

**Comment by arturovt** [comment]
Ok, this is super weird that `import Inputmask from 'inputmask'` exports an object with a `default` property, considering that this is a default import already. So this works:
```ts
import Inputmask from 'inputmask';

new Inputmask.default(this.inputMaskOptions).mask(this.nativeInputElement)
```
This happens because the `inputmask` package is still shipped in a UMD format to be compatible with all bundlers, I don't know how they compile the `inputmask` before publishing because they have a mangled code. I can guess that Angular 13 uses the latest version of Webpack 5 that has some major changes related to module resolution, especially for UMD modules. We have 2 options:
1) use `Inputmask.default`
2) do a check for `default` property, e.g.:
```js
import _Inputmask from 'inputmask';
const Inputmask = _Inpumask.default || _Inputmask
```

**Comment by ssougnez** [comment]
Funny, I had the exact same issue with the package "filesize".
I created a UI library that uses it and I was importing it like this:

`import * as filesize from 'filesize'`

And it used to work very well until ng13.
With ng13, I get a similar error than [this one](https://github.com/ngneat/input-mask/issues/40).
So I had to change the import to 

`import { partial } from 'filesize';`

And use it as a curried function.
The weird thing is that importing the library in the first way directly in the project using the library worked.

**Comment by ssougnez** [comment]
> Ok, this is super weird that `import Inputmask from 'inputmask'` exports an object with a `default` property, considering that this is a default import already. So this works:
> 
> ```ts
> import Inputmask from 'inputmask';
> 
> new Inputmask.default(this.inputMaskOptions).mask(this.nativeInputElement)
> ```
> 
> This happens because the `inputmask` package is still shipped in a UMD format to be compatible with all bundlers, I don't know how they compile the `inputmask` before publishing because they have a mangled code. I can guess that Angular 13 uses the latest version of Webpack 5 that has some major changes related to module resolution, especially for UMD modules. We have 2 options:
> 
> 1. use `Inputmask.default`
> 2. do a check for `default` property, e.g.:
> 
> ```js
> import _Inputmask from 'inputmask';
> const Inputmask = _Inpumask.default || _Inputmask
> ```
> 
> The second option is used by Angular Material for `moment`:
> 
> ```js
> import * as _moment from 'moment';
> import {default as _rollupMoment} from 'moment';
> 
> const moment = _rollupMoment || _moment;
> ```
> 
> `ng-packagr` uses Rollup internally so we can use the same approach.

I'm using inputmask (the dependency, not ngneat/input-mask) in one of my own library and this approach didn't seem to work (it didn't compile).

The only way I found to make it compile and run was:

`import 'inputmask';`

And use `Inputmask` everywhere I reference the dependency.
