### ISSUE TITLE
Disabled state is not honored

### ISSUE THREAD

**Issue by ssougnez** [ngneat/input-mask#46]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

It is possible to enter a value in a disabled input.

## Expected behavior

It should not be possible to enter value in a disabled input.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ogfsyp

## What is the motivation / use case for changing the behavior?

Standard behavior

## Environment

<pre><code>Angular CLI: 13.0.2
Node: 14.16.1
Package Manager: yarn 1.22.4
OS: win32 x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4

Browser:
- [x] Edge version 95
 
For Tooling issues:
- Node version: 14.16
- Platform:  Windows 
</code></pre>

**Comment by ssougnez** [comment]
I had a look and it seems the issue comes from the fact that "setDisabledState" was not implemented.
I created a PR to do so: https://github.com/ngneat/input-mask/pull/47

**Comment by penihel** [comment]
what about this. The problem exists at 5.0.0?

**Comment by gentoo90** [comment]
Could the fix of this be backported to `4.x` please?

**Comment by shhdharmen** [comment]
Done @gentoo90

**Comment by gentoo90** [comment]
@shhdharmen thank you!
