### ISSUE TITLE
Chrome Autofill 

### ISSUE THREAD

**Issue by danielehrhardt** [ngneat/input-mask#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When i am using Reactive Forms with the Input Mask and enter for example a E-Mail with the Chrome Autofiller then the Reactive Form does not detect the Value. 

When i remove the input mask it does work as expected. 

```
 <input
                                [formControl]="email"
                                required
                                matInput
                                placeholder="ddd@ddd.de"
                                [inputMask]="inputMask"
                            />

    emailInputMask = createMask({ alias: 'email' });
```

## Expected behavior

this.form.value 
should output the Value of the E-Mail Field. 

## Minimal reproduction of the problem with instructions

https://codesandbox.io/s/input-mask-autofill-10csi?file=/src/app/app.component.html

add a reactive form and a button to get the value of the reactive form.

## What is the motivation / use case for changing the behavior?

UX

## Environment

Angular 12

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14
- Platform:  Mac

**Comment by shhdharmen** [comment]
I think it's because of https://github.com/RobinHerbots/Inputmask/issues/2388 or https://github.com/RobinHerbots/Inputmask/issues/1330
