### ISSUE TITLE
Update Inputmask library

### ISSUE THREAD

**Issue by bogusweb** [ngneat/input-mask#57]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
How i can create pull request with update Inptumask dependency for both versions?

**Comment by shhdharmen** [comment]
@bogusweb what is the issue?

**Comment by bogusweb** [comment]
@shhdharmen i dont know how to create pull request which update library version for both versions this packages (like for angular 13+ and angular <13). Which branch is responsible for which version of this library?

**Comment by bogusweb** [comment]
New version Inputmask library fix few issues like https://github.com/ngneat/input-mask/issues/38

**Comment by shhdharmen** [comment]
You can first create a PR for Angular 13+, for that create branch from 'main` and raise a PR to `beta`.

**Comment by bogusweb** [comment]
ok thanks, i just created a PR to `main` branch but i didnt see a `beta` branch which contain older angular version

**Comment by bogusweb** [comment]
@shhdharmen thx for merge, now i have a question. Whether this change will also be introduced in the `4.x` version for <13?

**Comment by shhdharmen** [comment]
@bogusweb I had revert the commit, because commit message was not as per semver. Could you please create a PR again to `beta` branch? This time when you run `npm run commit`, select `feat`. Sorry for the rework.

Ref: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api
