### ISSUE TITLE
Error when reset reactiveform

### ISSUE THREAD

**Issue by aceleghin** [ngneat/input-mask#6]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I use inputMask with reactiveForms and I need to reset the form, sometimes I have the error in the image.
To reset the form I simply use form.reset().

![1](https://user-images.githubusercontent.com/27501745/123763380-012f5180-d8c4-11eb-8efe-ec0ffc384621.PNG)

## Environment

<pre><code>
Angular version: 12

Browser:
- [X] Chrome (desktop) version 91.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.17
- Platform:  Windows 
</code></pre>

**Comment by shhdharmen** [comment]
@aceleghin can you create a stackblitz to showcase the error?

**Comment by aceleghin** [comment]
Hi, I can't reproduce the error in the stackblitz, it is something like this
https://stackblitz.com/edit/angular-ivy-kfpedx?file=src/app/app.component.ts
it happens when I reset the field or the entire form.

**Comment by shhdharmen** [comment]
We can't help if error is not reproducible. Is it only happening in local? If so, can you create a repo with relevant code and steps to reproduce?

**Comment by drenda** [comment]
@shhdharmen I see your point and I agree. I'm following this problem as well and I noticed reference to the error line in the compiled .js.

I inspected the code:

```
 function c(e, t) {
                    var a = e ? e.inputmask : this, i = a.opts;
                    e.inputmask.refreshValue = !1, "function" == typeof i.onBeforeMask && (t = i.onBeforeMask.call(a, t, i) || t), 
                    d(e, !0, !1, t = t.toString().split("")), a.undoValue = a._valueGet(!0), (i.clearMaskOnLostFocus || i.clearIncomplete) && e.inputmask._valueGet() === o.getBufferTemplate.call(a).join("") && -1 === o.getLastValidPosition.call(a) && e.inputmask._valueSet("");
                }
```

In the last line `t.toString().split("")` cannot work if the value of t is null as in the case described from @aceleghin. It seems to me it is missing some check on that variable to see if actually you can perform those actions on it.
Do you have some hints to give me in order to point me in the right direction and create a reproducible code? I feel we can find the bug somewhere.

Thanks

**Comment by shhdharmen** [comment]
@drenda Thanks for your inputs. You can create a new Angular project, with only code needed which gives that error. I can can then try to debug.

**Comment by aceleghin** [comment]
Hi, here is the example.
https://stackblitz.com/edit/angular-ivy-qthckx?file=src/app/app.component.html
If you click on the reset button in the example you can see the error in the console.

p.s. as mentioned in this issue it is wrong that the field is not valid if empty (and not required), I don't think it is related but both of them need to be fixed.
https://github.com/ngneat/input-mask/issues/12

**Comment by shhdharmen** [comment]
Thanks @aceleghin.

The issue is in the inputmask library, it doesn't handle null value properly. Ref: https://github.com/RobinHerbots/Inputmask/issues/1485

But, we can handle it in `writeValue` function of directive. Do you want to create a PR for it?

**Comment by aceleghin** [comment]
It is just that line:
`  writeValue(value: string): void {
    if (value) {
      this.renderer.setProperty(this.elementRef.nativeElement, 'value', value);
    }
  }`
  
I am not very familiar with contributing on GitHub so if you want a PR I need some info on how to do it right, or you can correct it faster on your own.

**Comment by shhdharmen** [comment]
You can easily find out resources online. And also check our contributing guidelines.

**Comment by shhdharmen** [comment]
@aceleghin are you working on it?
