### ISSUE TITLE
Cut & paste problem

### ISSUE THREAD

**Issue by bogusweb** [ngneat/input-mask#68]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
 If u write a value with inputMask and 'cut' this value with `ctrl/cmd + x` then the value that is cut is not passed to the clipboard. This case work in main package based on JS.
This bug occurs in `4.x` and `5.x` version of this library.

Angular v13 with @ngneat/input-mask@5.2.0 - https://stackblitz.com/edit/angular-ivy-vpnlko
Angular v11 with @ngneat/input-mask@4.1.1 - https://stackblitz.com/edit/angular-ivy-aq5gkw

## Expected behavior
In clipboard u have a cutted value from input with mask

## Minimal reproduction of the problem with instructions

1. Write a value, like `111.111.111`
2. Cut this value from input with mask (`ctrl/cmd+x`)
3. Try paste this value in input with mask
4. Value is not pasted

## Environment

<pre><code>
Angular version: x.x.x

Browser:
- [] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DywiTom** [comment]
Any update?

**Comment by shhdharmen** [comment]
Is this issue happening in localhost or any other actual deployment?
