### ISSUE TITLE
Emit a phantom value on start

### ISSUE THREAD

**Issue by bogusweb** [ngneat/input-mask#70]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Form control with mask, emit phantom value (check console.log in stackblitz link)

Angular v13 with @ngneat/input-mask@5.2.0 - https://stackblitz.com/edit/angular-ivy-vpnlko
Angular v11 with @ngneat/input-mask@4.1.1 - https://stackblitz.com/edit/angular-ivy-aq5gkw

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
Once inputmask is set on input element, we need to call `updateValueAndValidity` and hence it's happening. Not an issue.
