### ISSUE TITLE
groupSeparator NOT WORKING

### ISSUE THREAD

**Issue by denes** [ngneat/input-mask#71]
groupSeparator NOT WORKING

And how can I change decimal separator?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

<img width="1406" alt="Screen Shot 2022-05-15 at 13 27 03" src="https://user-images.githubusercontent.com/175498/168483275-1f3fb3dc-1208-4a8b-8825-f6e924b8fa4e.png">

**Comment by shhdharmen** [comment]
Can you please create stackblitz to demonstrate the issue?

**Comment by JorgeAlonsoLopez** [comment]
Hello, I have the same problem, I hope this helps.
[https://stackblitz.com/edit/angular-ivy-yv9v9w?file=src/app/app.module.ts](https://stackblitz.com/edit/angular-ivy-yv9v9w?file=src/app/app.module.ts)

**Comment by shhdharmen** [comment]
Please check native inputmask library options.
