### ISSUE TITLE
Add missing "alias" documentation

### ISSUE THREAD

**Issue by mrmokwa** [ngneat/input-mask#73]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

Can't find any documentation about `alias`:
What's its purpose?
List of available alias?

**Comment by shhdharmen** [comment]
https://github.com/RobinHerbots/Inputmask#aliases
