### ISSUE TITLE
Currency input mask not updating value when user backspaces over cents

### ISSUE THREAD

**Issue by nickeeromo** [ngneat/input-mask#74]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Even in the example at https://github.com/ngneat/input-mask#3-currency, this behavior can be seen.

In my application, for example, the value in the field begins as something like 383.83. If the user goes to the end and backspaces over the 3, a zero replaces it. But then when I check the value, it is still 383.83. When backspacing over digits on the left side of the decimal, the value gets updated. So it's like the trailing zeros aren't recognized until a ones place or higher are updated.

## Expected behavior

The value should be updated.

## Minimal reproduction of the problem with instructions
Again, you could follow the setup at https://github.com/ngneat/input-mask#3-currency. Currently this looks like:

```
@Component({
  template: `
    <input
      [inputMask]="currencyInputMask"
      [formControl]="currencyFC"
      placeholder="$ 0.00"
    />
  `,
})
export class AppComponent {
  currencyInputMask = createMask({
    alias: 'numeric',
    groupSeparator: ',',
    digits: 2,
    digitsOptional: false,
    prefix: '$ ',
    placeholder: '0',
  });
  currencyFC = new FormControl('');
}
```

Update: I added a Stackblitz for simplicity. It's in Angular 14, but the version of Angular is not the issue: https://stackblitz.com/edit/angular-ivy-exhxta?file=src/app/app.component.ts

## What is the motivation / use case for changing the behavior?

In any application that deals with currency, every cent matters. If the end user believes they are paying even 1 cent less than they really are, it could cause problems for the consumers of this library.

## Environment

<pre><code>
Angular version: 13.0.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

I also want to say I switched from another library to this one for masking currency _because_ the other masking library refused to display trailing zeros at all, so you guys are already a leg up on them. Thank you!

**Comment by Eugeno** [comment]
Same problem with `delete` button and with `minus` sign.
Looks like it's related to https://github.com/RobinHerbots/Inputmask/issues/2621

**Comment by shhdharmen** [comment]
As it's an issue in original library, closing this one.
