### ISSUE TITLE
NG0303: Can't bind to 'inputMask' since it isn't a known property of 'input' (used in the 'xyz' component template).

### ISSUE THREAD

**Issue by SheldonHage** [ngneat/input-mask#80]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

**Input mask does not bind to input elements.**  I have multiple projects using @neat/input-mask successfully.  This is my first attempt at using it in an Ionic project.

## Expected behavior

I am expecting the [inputMask]="someInputMask" to work as it does in my other project.

## Minimal reproduction of the problem with instructions

1. In a new Angular/Ionic/Capacitor project:  **ng add @ngneat/input-mask;**  
2. verify app.modules.ts import: **{ InputMaskModule } from '@ngneat/input-mask';** 
3. verify app.modules.ts import declaration: **imports: [InputMaskModule]** 
4. verify app.component.ts import: **import { createMask } from '@ngneat/input-mask';**
5. create mask in app.component.ts:    **this.phoneInputMask = createMask('(999) 999-9999');**
6. bind in app.component.html:  **<input [inputMask]='phoneInputMask' formControlName="phone" required>**
7.  receive error in app.component.html:  **Can't bind to 'inputMask' since it isn't a known property of 'input'**

## Environment

<pre><code>
Ionic 6.20.1
Capacitor 4.1.0
Angular version: 14.2.0

@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@angular/fire                   7.4.1
@angular/google-maps            14.2.2
@schematics/angular             14.2.1
rxjs                            6.6.7
typescript                      4.7.4

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.8.2  
- Platform:  Macos

Others:
- Microsoft VS Code

</code></pre>
<img width="960" alt="input_mask_binding" src="https://user-images.githubusercontent.com/49240336/190457083-52fce920-fa05-4f75-8ee2-3ea36a370540.png">

**Comment by shhdharmen** [comment]
Please create a stackblitz to showcase this error.
