### ISSUE TITLE
Label asterisk (Required)

### ISSUE THREAD

**Issue by denes** [ngneat/input-mask#82]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The Label with (*) for fields required is not showing

## Expected behavior

Show Label with (*) for fields required

## Minimal reproduction of the problem with instructions

![image](https://user-images.githubusercontent.com/175498/194613214-330723a0-ff49-4bec-bd14-88e70b07cd07.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version XX
- [ x ] Chrome (Android) version XX
- [ x ] Chrome (iOS) version XX
- [ x ] Firefox version XX
- [ x ] Safari (desktop) version XX
- [ x ] Safari (iOS) version XX
- [ x ] IE version XX
- [ x ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
I don't think it's related to input-mask. If it is, please create a stackblitz showing that asterisk is visible/hidden without/with input-mask.
