### ISSUE TITLE
Cursor jumps on first digit

### ISSUE THREAD

**Issue by leon-meka** [ngneat/input-mask#83]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Cursor jumps to the right of the first numeric position, when having a groupSelector set. 

Example:
![b9cbee73-b120-4b39-be65-2fbe19e7268f](https://user-images.githubusercontent.com/108529603/195368275-61aea009-e530-477e-9278-fa85fb3291a6.gif)

## Expected behavior
Cursor should be positioned to the left of the first numeric position.

## Minimal reproduction of the problem with instructions
(see gif above)

## Environment
https://stackblitz.com/edit/angular-ivy-ikuzc4?file=src%2Fapp%2Fapp.component.ts

Browser:
Every browser

**Comment by shhdharmen** [comment]
It's the behaviour of original library.
