### ISSUE TITLE
Bug: Input is not working with inputmask@5.0.7

### ISSUE THREAD

**Issue by DywiTom** [ngneat/input-mask#85]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request
- [ ] Other... Please describe:

## Current behavior

Number is not correct after input.

## Minimal reproduction of the problem with instructions

See Stackblitz:
https://stackblitz.com/edit/input-mask-dywitom-zf1ljc

## Environment

Angular version:
<pre><code>
"dependencies": {
    "@angular/animations": "^14.2.7",
    "@angular/cdk": "^14.2.5",
    "@angular/common": "^14.2.7",
    "@angular/compiler": "^14.2.7",
    "@angular/core": "^14.2.7",
    "@angular/forms": "^14.2.7",
    "@angular/material": "^14.2.5",
    "@angular/material-luxon-adapter": "^14.2.5",
    "@angular/platform-browser": "^14.2.7",
    "@angular/platform-browser-dynamic": "^14.2.7",
    "@angular/router": "^14.2.7",
    "@fullcalendar/web-component": "^6.0.0-beta.1",
    "@ngneat/input-mask": "^5.2.0",
    "hammerjs": "^2.0.8",
    "inputmask": "^5.0.7",
    "luxon": "^2.3.2",
    "rxjs": "^7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "^0.11.8"
  }
</code></pre>

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v16.13.0
- Platform:  Windows

**Comment by shhdharmen** [comment]
It's working on your stackblitz link.

**Comment by DywiTom** [comment]
No sorry, it's not.
Write 1234567 and lose focus. It will become 1,00

**Comment by shhdharmen** [comment]
It's becuase of the options you're using. Use below option and see it's working fine.

```
{
    alias: 'numeric',
    groupSeparator: ',',
    digits: 2,
    digitsOptional: false,
    prefix: '$ ',
    placeholder: '0',
}
```
