### ISSUE TITLE
Bug: Value stays negative after mark and replace

### ISSUE THREAD

**Issue by DywiTom** [ngneat/input-mask#86]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request
- [ ] Other... Please describe:

## Current behavior

- Write a positive number
- Press -
- Mark the whole number
- Write a new number
- Bug: Value stays negative

## Minimal reproduction of the problem with instructions

See Stackblitz:
https://stackblitz.com/edit/input-mask-dywitom-wgx7sa

## Environment

Angular version:
<pre><code>
"dependencies": {
    "@angular/animations": "^14.2.7",
    "@angular/cdk": "^14.2.5",
    "@angular/common": "^14.2.7",
    "@angular/compiler": "^14.2.7",
    "@angular/core": "^14.2.7",
    "@angular/forms": "^14.2.7",
    "@angular/material": "^14.2.5",
    "@angular/material-luxon-adapter": "^14.2.5",
    "@angular/platform-browser": "^14.2.7",
    "@angular/platform-browser-dynamic": "^14.2.7",
    "@angular/router": "^14.2.7",
    "@fullcalendar/web-component": "^6.0.0-beta.1",
    "@ngneat/input-mask": "^5.2.0",
    "hammerjs": "^2.0.8",
    "inputmask": "^5.0.5",
    "luxon": "^2.3.2",
    "rxjs": "^7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "^0.11.8"
  }
</code></pre>

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v16.13.0
- Platform:  Windows

**Comment by shhdharmen** [comment]
What do you mean by "Mark the whole number"?

**Comment by DywiTom** [comment]
- select the whole number and delete it

**Comment by shhdharmen** [comment]
It's working fine in your stackblitz link. Please attach video.

**Comment by hakimio** [comment]
![negative-number](https://user-images.githubusercontent.com/768105/200509893-0915e4a8-8330-4392-86b6-3bce425accdf.gif)

**Comment by shhdharmen** [comment]
Can you check if this is an issue with original library?

**Comment by hakimio** [comment]
Yes, it has pretty similar behavior, except it only adds "-" sign after you tipe the second digit.
https://robinherbots.github.io/Inputmask/

**Comment by shhdharmen** [comment]
As it's issue with original library, closing this issue.
