### ISSUE TITLE
Angular mat-datePicker missing event dateChange

### ISSUE THREAD

**Issue by Micha10** [ngneat/input-mask#99]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If using inputmask with a mat-datepicker, the event (dataChange) is not sent when leaving the control (blur)

## Expected behavior

Ability to receive the same messages as without inputmask

## Minimal reproduction of the problem with instructions

https://stackblitz.com/github/Micha10/input-mask

Please open the console. 

Input a date in the first datepicker (i.e 01.01.2022). Each letter will post an entry in the console (input1). If you leave the control with tab, (change1) will be shown.

Now do the same with the second control, the one with a mask. If the entered text is a date (input2) is shown.

But if you leave the control with tab, (change2) is missing.
```

<mat-form-field>
    <input matInput [matDatepicker]="picker1" placeholder="Choose a date" [ngModel]="date1"
             (dateInput)="addEvent('input1', $event)" (dateChange)="addEvent('change1', $event)"
    >
    <mat-datepicker-toggle matSuffix [for]="picker1"></mat-datepicker-toggle>
    <mat-datepicker #picker1></mat-datepicker>
  </mat-form-field>
```

```
<input matInput [matDatepicker]="picker2" placeholder="Choose a date" [ngModel]="date2"
           [inputMask]="dateInputMask"  (dateInput)="addEvent('input2', $event)" (dateChange)="addEvent('change2', $event)"
    >
```
```
  addEvent(type: string, event: MatDatepickerInputEvent<Date>) {
    console.log((`${type}: ${event.value}`));
  }
```

## Environment

<pre><code>
Angular version: 15.2.9

Browser:
- [x] Chrome (desktop) version 113.0.5672
- [X] Librewolf version 111.0.1-1
 
For Tooling issues:
- Platform:   Windows

**Comment by shhdharmen** [comment]
The stackblitz project is not running.

**Comment by Micha10** [comment]
> The stackblitz project is not running.

Sorry, I've changed a few things. Locally it's working, but stackblitz seems to have issues with moment. 
Fixes. Project is working again. 
Sorry for the trouble

**Comment by shhdharmen** [comment]
Can you please publish your project on github?

**Comment by Micha10** [comment]
The link above generates a stackblitz from the gitgub repo. You can find the original repo here: https://github.com/Micha10/input-mask

**Comment by shhdharmen** [comment]
As it's working locally, closing this issue.

**Comment by Micha10** [comment]
Hi, have you tried the SECOND input? As I wrote above. The first is without mask and it's working

The second is logging "input2" events while typing but it does not send "change2" while the first does

**Comment by shhdharmen** [comment]
You're trying to use features from 2 libraries together: Angular Material Datepicker and @ngneat/input-mask. They both rely differently on input events. And hence, it's not recommended to use both of them together.
